name: HATIR
channels:
  - xformers
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - ca-certificates=2025.12.2
  - cffi=2.0.0
  - cudatoolkit=11.3.1
  - future=1.0.0
  - intel-openmp=2021.4.0
  - ld_impl_linux-64=2.44
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libprotobuf=3.20.3
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libxcb=1.17.0
  - libzlib=1.3.1
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.5
  - ninja-base=1.13.1
  - numpy-base=1.23.1
  - openssl=3.0.19
  - pip=25.3
  - pthread-stubs=0.3
  - pycparser=2.23
  - python=3.9.21
  - readline=8.3
  - six=1.17.0
  - sqlite=3.51.1
  - tk=8.6.15
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - wheel=0.45.1
  - xformers=0.0.20
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - yaml=0.2.5
  - zlib=1.3.1
  - pip:
      - absl-py==2.3.1
      - addict==2.4.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - albumentations==1.3.0
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - altair==6.0.0
      - antlr4-python3-runtime==4.8
      - async-timeout==5.0.1
      - attrs==25.4.0
      - av==14.2.0
      - blinker==1.9.0
      - braceexpand==0.1.7
      - cachetools==6.2.6
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - click==8.1.8
      - clip==1.0
      - colorama==0.4.6
      - contourpy==1.3.0
      - crcmod==1.7
      - cryptography==46.0.4
      - cycler==0.12.1
      - einops==0.3.0
      - filelock==3.14.0
      - fonttools==4.60.2
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - ftfy==6.3.1
      - gitdb==4.0.12
      - gitpython==3.1.46
      - grpcio==1.76.0
      - hf-xet==1.2.0
      - huggingface-hub==0.36.0
      - idna==3.11
      - imageio==2.9.0
      - imageio-ffmpeg==0.4.2
      - importlib-metadata==8.7.1
      - importlib-resources==6.5.2
      - invisible-watermark==0.2.0
      - jinja2==3.1.6
      - jmespath==0.10.0
      - joblib==1.5.3
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.7
      - kornia==0.6.0
      - lazy-loader==0.4
      - lightning-utilities==0.15.2
      - lpips==0.1.4
      - markdown==3.9
      - markdown-it-py==3.0.0
      - markupsafe==3.0.3
      - matplotlib==3.9.4
      - mdurl==0.1.2
      - mmcv==2.2.0
      - mmengine==0.10.7
      - model-index==0.1.11
      - mpmath==1.3.0
      - multidict==6.7.1
      - mypy-extensions==1.1.0
      - narwhals==2.15.0
      - networkx==3.2.1
      - ninja==1.13.0
      - numpy==2.0.2
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.8.90
      - omegaconf==2.1.1
      - open-clip-torch==2.0.2
      - opencv-python==4.6.0.66
      - opencv-python-headless==4.5.5.64
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openxlab==0.1.3
      - ordered-set==4.1.0
      - oss2==2.17.0
      - packaging==24.2
      - pandas==2.1.4
      - pillow==11.3.0
      - piq==0.8.0
      - platformdirs==4.4.0
      - propcache==0.4.1
      - protobuf==3.20.3
      - pyarrow==21.0.0
      - pycryptodome==3.23.0
      - pydeck==0.9.1
      - pydeprecate==0.3.1
      - pygments==2.19.2
      - pympler==1.1
      - pyparsing==3.3.2
      - pyre-extensions==0.0.23
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==1.4.2
      - pytz==2023.4
      - pywavelets==1.6.0
      - pyyaml==6.0.3
      - qudida==0.0.4
      - referencing==0.36.2
      - regex==2026.1.15
      - requests==2.28.2
      - rich==13.4.2
      - rpds-py==0.27.1
      - safetensors==0.7.0
      - scikit-image==0.20.0
      - scikit-learn==1.6.1
      - scipy==1.9.1
      - semver==3.0.4
      - setuptools==60.2.0
      - smmap==5.0.2
      - streamlit==1.12.1
      - streamlit-drawable-canvas==0.8.0
      - sympy==1.14.0
      - tabulate==0.9.0
      - taming-transformers-rom1504==0.0.6
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - termcolor==3.1.0
      - test-tube==0.7.5
      - threadpoolctl==3.6.0
      - tifffile==2024.8.30
      - tokenizers==0.15.2
      - toml==0.10.2
      - tomli==2.4.0
      - torch==1.13.1+cu117
      - torchaudio==0.12.1+cu113
      - torchmetrics==0.6.0
      - torchvision==0.13.1+cu113
      - tornado==6.5.4
      - tqdm==4.65.2
      - transformers==4.36.1
      - triton==3.3.0
      - typing-inspect==0.9.0
      - tzdata==2025.3
      - tzlocal==5.3.1
      - urllib3==1.26.20
      - validators==0.35.0
      - watchdog==6.0.0
      - wcwidth==0.5.2
      - webdataset==0.2.5
      - werkzeug==3.1.5
      - yapf==0.43.0
      - yarl==1.22.0
      - zipp==3.23.0
prefix: /root/miniconda3/envs/HATIR
