model:
  base_learning_rate: 5.0e-5
  target: ldm.models.autoencoder.VideoAutoencoderKLResi
  params:
    # for training only
    # ckpt_path: ./checkpoints/TAD.ckpt
    monitor: "val/rec_loss"
    embed_dim: 4
    fusion_w: 1.0
    freeze_dec: False
    synthesis_data: False
    version: 1
    lossconfig:
      target: ldm.modules.losses.LPIPSWithDiscriminator
      params:
        num_frames: 6
        disc_start: 501
        pixelloss_weight: 1.0
        diffloss_weight: 0.5
        thermalloss_weight: 0.5
        edgeloss_weight: 0.5
        # freqloss_weight: 0
        perceptual_weight: 0.5
        kl_weight: 0
        disc_weight: 0.025
        disc_factor: 1.0 
        # disc_weight: 0
        # disc_factor: 0
        flownet_config:
          target: basicsr.archs.spynet_arch.SpyNet
          params: 
            load_path: ./checkpoints/spynet_sintel_final-3d2a1287.pth
    ddconfig:
      double_z: true
      num_frames: 6
      z_channels: 4
      resolution: 512
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult:
      - 1
      - 2
      - 4
      - 4
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0
    
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 8
    wrap: True
    train:
      target: basicsr.data.single_video_dataset.REDSAutoencoderDataset
      params:
        dataroot_gt: ./output_l/gt
        dataroot_lq: ./output_l/lq
        dataroot_ps: ./output_l/phasor
        dataroot_lt: ./output_l/lantent
        dataroot_fl: ./output_l/flow
        seq_num: 645
        frame_num: 30
        val_partition: HATIR
        test_mode: false
        io_backend:
          type: disk
        load_fix_indices_only: true

        num_frame: 6
        gt_size: 512
        interval_list: [1]
        random_reverse: false
        use_hflip: true
        use_rot: false
        flip_sequence: false

        scale: 4
    validation:
      target: basicsr.data.single_video_dataset.REDSAutoencoderDataset
      params:
        dataroot_gt: ./output_l/gt
        dataroot_lq: ./output_l/lq
        dataroot_ps: ./output_l/phasor
        dataroot_lt: ./output_l/lantent
        dataroot_fl: ./output_l/flow
        seq_num: 130
        frame_num: 30
        val_partition: HATIR
        test_mode: true
        io_backend:
          type: disk
        load_fix_indices_only: true

        num_frame: 6
        gt_size: 512
        interval_list: [1]
        random_reverse: false
        use_hflip: true
        use_rot: false
        flip_sequence: false

        scale: 4

lightning:
  modelcheckpoint:
    params:
      every_n_train_steps: 1500
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 300
        max_images: 5
        n_row: 5
        increase_log_steps: False
  trainer:
    benchmark: True
    max_steps: 800000
    accumulate_grad_batches: 8
